Feat/integration groups and feed with api
Move-HandsOn/move-frontend pull request #32
Opened 2024-11-16 08:18 UTC by anjosdelacerda

Descrição
Por favor, inclua um resumo das alterações e da issue relacionada. Também inclua motivação e contexto relevantes.

Corrige # (issue)

Tipo de Alteração
Por favor, exclua as opções que não forem relevantes.

[ x] Novo recurso (alteração que não quebra e adiciona funcionalidade)

Como Isso Foi Testado?
Por favor, descreva os testes que você realizou para verificar suas alterações. Forneça instruções para que possamos reproduzi-las. Liste também quaisquer detalhes relevantes da configuração dos seus testes.

[x] teste manual com a api e amostra do grafico

Checklist:
[ x] Meu código segue as diretrizes de estilo deste projeto
[x ] Eu revisei meu próprio código
[ ] Comentei meu código, especialmente em áreas de difícil compreensão
[ ] Fiz alterações correspondentes na documentação
[ ] Minhas alterações não geram novos avisos
[ ] Adicionei testes que comprovam que minha correção é eficaz ou que meu recurso funciona
[ ] Testes de unidade novos e existentes passam localmente com minhas alterações
[ ] Quaisquer alterações dependentes foram mescladas e publicadas nos módulos downstream

2024-11-16 08:19 UTC, anjosdelacerda commented
integração de feed com a api. As postagens não foram integradas, pois na API não é encontrado nenhuma lista na rota GET /posts

2024-11-19 18:42 UTC, danieldeandradelopes requested changes

2024-11-19 18:42 UTC, danieldeandradelopes commented on src/pages/Feed/Feed.tsx
>      console.log(`Usuário quer participar do grupo ${groupId}`);
Remover console log.

2024-11-19 18:42 UTC, danieldeandradelopes commented on src/services/requests.ts
> +  isParticipation: boolean;
Essa propriedade existe em Meus Grupos, lá no backend no caso?

2024-11-19 18:42 UTC, danieldeandradelopes commented on src/pages/Feed/Feed.tsx
> +interface GroupsProps {
Um nome melhor seria

IGroups e não GroupsProps, o setGroups não é um component para receber props, mas um estado.

2024-11-19 18:42 UTC, danieldeandradelopes commented on src/components/GroupCard/GroupCard.tsx
> +interface GroupsProps {
Um nome melhor seria:

GroupCardProps

2024-11-19 18:42 UTC, danieldeandradelopes commented on src/components/GroupCard/GroupCard.tsx
> +function GroupCard({ group_image, name, members, group_type, onJoin, isParticipation }: GroupsProps) {
Porque renomear todas props?

2024-11-19 18:42 UTC, danieldeandradelopes commented on src/components/ListMyGroups/ListMyGroups.tsx
> +interface GroupsProps {
IGroup, pois PROPS é para components.

2024-11-21 07:24 UTC, closed without merging